# Rust cache
.rust_cache:
  cache:
    key:
      files:
        - Cargo.lock
      prefix: $CI_COMMIT_REF_SLUG
    policy: pull
    untracked: true
    paths:
      - .cargo/
      - target/release/
