version: "3"
services:
  node_alice:
    image: tributary.semantic-network.tech:5050/semnet/tidefi/back/tidefi-substrate-node/node:dev
    container_name: alice
    command: >
      /usr/local/bin/tidefi-node --base-path /tmp/alice --chain testnet --alice --port 30333 --ws-port 9944 --rpc-port 9933 --node-key 0000000000000000000000000000000000000000000000000000000000000001 --validator --ws-external --rpc-methods=unsafe --rpc-cors=all
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - "tidefi-data-alice:/data"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    image: tributary.semantic-network.tech:5050/semnet/tidefi/back/tidefi-substrate-node/node:dev
    container_name: bob
    command: >
      /usr/local/bin/tidefi-node --base-path /tmp/bob --chain testnet --bob --port 30334 --ws-port 9945 --rpc-port 9934 --validator --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
    ports:
      - "30334:30333"
      - "9934:9933"
      - "9945:9944"
    volumes:
      - "tidefi-data-bob:/data"
    links:
      - "node_alice:alice"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

volumes:
  tidefi-data-alice:
  tidefi-data-bob:

networks:
  testing_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
