version: "3"
services:
  testnet_validator:
    image: tributary.semantic-network.tech:5050/semnet/tidefi/back/tidefi-substrate-node/node:testnet
    command: >
        /usr/local/bin/tidefi-node --base-path=/data --chain=testnet --name="testnet-validator-01" --validator --bootnodes /ip4/10.100.2.18/tcp/30333/p2p/12D3KooWEQmRfrvLbDcmxm8dGpFqkpeyUm5rLTY2SjKH9VJxE7rj
    ports:
      - "30333:30333"
      - "9944:9944"
    volumes:
      - "tidefi-data:/data"

volumes:
  tidefi-data:
