version: "3"
services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/srv/certs/:/etc/nginx/ssl:ro"
  node:
    image: tributary.semantic-network.tech:5050/semnet/tidefi/back/tidefi-substrate/node:dev
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
      - "3000:3000"
