rust-nightly:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/paritytech/ci-linux:staging
  rules:
    - if: $NIGHTLY_TEST == "1"
  script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@tributary.semantic-network.tech" > ~/.git-credentials
    - curl -L -O https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz
    - ./scripts/init.sh
    - SKIP_WASM_BUILD=1 cargo check --release
    - pushd node && cargo check --features=runtime-benchmarks --release
    - SKIP_WASM_BUILD=1 cargo +nightly clippy -Z unstable-options --all-targets --release -- -D warnings
