rust-nightly:
  stage: test
  extends: .rust_cache
  image: paritytech/ci-linux:production
  rules:
    - if: $NIGHTLY_TEST == "1"
  script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@tributary.semantic-network.tech" > ~/.git-credentials
    - ./scripts/init.sh
    - rustup component add clippy rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
    - SKIP_WASM_BUILD=1 cargo check --all --release
    - SKIP_WASM_BUILD=1 cargo +nightly clippy -Z unstable-options --all-targets --release --all -- -D warnings
