[package]
name = "tidechain-cli"
version = "0.1.0"
authors = ["Semantic Network Team"]
edition = "2021"
license = "GNU GPL v3"
homepage = ""
repository = ""

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on Linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.13"
thiserror = "1.0.30"
structopt = "0.3.8"
futures = "0.3.19"
sp-core = { git = "https://github.com/tide-labs/substrate", branch = "tidechain" }
sc-cli = { git = "https://github.com/tide-labs/substrate", branch = "tidechain", features = ["wasmtime"] }
sc-service = { git = "https://github.com/tide-labs/substrate", branch = "tidechain", features = ["wasmtime"] }
tidechain-service = { path = "../node/service" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { git = "https://github.com/tide-labs/substrate", branch = "tidechain" }
frame-benchmarking-cli = { git = "https://github.com/tide-labs/substrate", branch = "tidechain" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/tide-labs/substrate", branch = "tidechain" }

[features]
default = [ "tidechain-native" ]
try-runtime = []
runtime-benchmarks = [
	"tidechain-service/runtime-benchmarks",
]

tidechain-native = [ "tidechain-service/tidechain-native" ]
hertel-native = [ "tidechain-service/hertel-native" ]