#!/bin/sh

set -e

action="$1"
config_file="/etc/default/tidechain"

if [ "$action" = "configure" ]; then
  # Make user and group
  getent group tidechain >/dev/null 2>&1 || addgroup --system tidechain
  getent passwd tidechain >/dev/null 2>&1 ||
    adduser --system --home /home/tidechain --disabled-password \
    --ingroup tidechain tidechain
  if [ ! -e "$config_file" ]; then
    echo 'TIDECHAIN_CLI_ARGS=""' > /etc/default/tidechain
  fi
fi
